--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Jasson44/ClaimAndProtect
build-by-default: true
branches:
- main
projects:
  ClaimAndProtect:
    path: ""
    type: plugin
    lint: false
    libs:
      - src: Muqsit/SimplePacketHandler
        branch: pm5
        version: ^0.1.5
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
